spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.101.37.18:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver


  cloud:
    nacos:
      discovery:
        server-addr: 47.101.37.18:8848

    alicloud:
      access-key: LTAI5tJnuz62L8xA18Ww86eP
      secret-key: UNjFwBwW4sBzlVr9el8wojHmV9teZk
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com




  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
  error:
    include-binding-errors: always
    include-message: always

logging:
  level:
    com.miaojinbo.gulimall: debug





