spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.37.18:8848
    alicloud:
      access-key: LTAI5tJnuz62L8xA18Ww86eP
      secret-key: UNjFwBwW4sBzlVr9el8wojHmV9teZk
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-miaojinbo
  application:
    name: gulimall-third-party

server:
  port: 3000


